let education = {
    data: [
    {"id":"1","title":"Associate of Science","type":"Degree"},
    {"id":"2","title":"Associate of Applied Arts","type":"Degree"},
    {"id":"3","title":"Associate of Applied Science","type":"Degree"},
    {"id":"4","title":"Bachelor of Arts","type":"Degree"},
    {"id":"5","title":"Associate in Nursing","type":"Degree"},
    {"id":"6","title":"Master of Arts","type":"Degree"},
    {"id":"7","title":"Master of Arts in Teaching","type":"Degree"},
    {"id":"9","title":"Bachelor of Applied Mathematics","type":"Degree"},
    {"id":"10","title":"Bachelor of Architecture","type":"Degree"},
    {"id":"11","title":"BBA (Bachelor of Business Administration)","type":"Degree"},
    {"id":"13","title":"Bachelor of Chemical Engineering","type":"Degree"},
    {"id":"14","title":"BEd (Bachelor of Education)","type":"Degree"},
    {"id":"16","title":"Bachelor of Fine Arts","type":"Degree"},
    {"id":"17","title":"Bachelor of Journalism","type":"Degree"},
    {"id":"18","title":"Bachelor of Literature","type":"Degree"},
    {"id":"19","title":"Bachelor of Music","type":"Degree"},
    {"id":"20","title":"Bachelor of Marine Science","type":"Degree"},
    {"id":"21","title":"Bachelor of Nursing","type":"Degree"},
    {"id":"22","title":"Bachelor of Pharmacy","type":"Degree"},
    {"id":"24","title":"BS (Business Administration)","type":"Degree"},
    {"id":"25","title":"BS (Education)","type":"Degree"},
    {"id":"27","title":"BS (Nursing)","type":"Degree"},
    {"id":"28","title":"Business Studies","type":"Degree"},
    {"id":"29","title":"Bachelor of Professional Studies","type":"Degree"},
    {"id":"31","title":"Chemical Engineer","type":"Degree"},
    {"id":"32","title":"Doctor of Arts","type":"Degree"},
    {"id":"33","title":"Doctor of Applied Science","type":"Degree"},
    {"id":"34","title":"Doctor of Business Administration","type":"Degree"},
    {"id":"35","title":"Doctor of Chiropractic","type":"Degree"},
    {"id":"36","title":"Doctor of Divinity","type":"Degree"},
    {"id":"37","title":"Doctor of Education","type":"Degree"},
    {"id":"38","title":"Doctor of Library Science","type":"Degree"},
    {"id":"39","title":"Doctor of Dental Medicine","type":"Degree"},
    {"id":"40","title":"Doctor of Medical Science","type":"Degree"},
    {"id":"41","title":"Doctor of Public Administration","type":"Degree"},
    {"id":"42","title":"Doctor of Public Health","type":"Degree"},
    {"id":"43","title":"Doctor of Religious Education","type":"Degree"},
    {"id":"44","title":"Doctor of Social Welfare or Doctor of Social Work","type":"Degree"},
    {"id":"45","title":"Doctor of Science","type":"Degree"},
    {"id":"46","title":"Doctor of Veterinary Medicine","type":"Degree"},
    {"id":"47","title":"Doctor of Education","type":"Degree"},
    {"id":"48","title":"Education Specialist","type":"Degree"},
    {"id":"49","title":"ME (Master of Engineering)","type":"Degree"},
    {"id":"50","title":"Engineer of Mines","type":"Degree"},
    {"id":"51","title":"Engineer of Metallurgy","type":"Degree"},
    {"id":"52","title":"Industrial Engineer or Industrial Engineering","type":"Degree"},
    {"id":"53","title":"Doctor of Laws","type":"Degree"},
    {"id":"54","title":"Doctor of Juristic Science","type":"Degree"},
    {"id":"55","title":"Doctor of Humane Letters","type":"Degree"},
    {"id":"56","title":"Bachelor of Letters","type":"Degree"},
    {"id":"57","title":"Master of Letters","type":"Degree"},
    {"id":"58","title":"Bachelor of Law","type":"Degree"},
    {"id":"59","title":"Doctor of Laws","type":"Degree"},
    {"id":"60","title":"Master of Law","type":"Degree"},
    {"id":"62","title":"Master of Aeronautical Engineering","type":"Degree"},
    {"id":"63","title":"MBA (Master of Business Administration)","type":"Degree"},
    {"id":"64","title":"Master of Computer Science","type":"Degree"},
    {"id":"65","title":"Doctor of Medicine","type":"Degree"},
    {"id":"66","title":"Master of Divinity","type":"Degree"},
    {"id":"68","title":"MEd (Master of Education)","type":"Degree"},
    {"id":"70","title":"Master of Fine Arts","type":"Degree"},
    {"id":"71","title":"Master of Hospital Administration","type":"Degree"},
    {"id":"72","title":"Master of Library Science","type":"Degree"},
    {"id":"73","title":"Master of Music","type":"Degree"},
    {"id":"74","title":"Master of Nursing","type":"Degree"},
    {"id":"75","title":"MPA (Master of Public Administration)","type":"Degree"},
    {"id":"76","title":"MSc (Master of Science)","type":"Degree"},
    {"id":"78","title":"Master of Social Work","type":"Degree"},
    {"id":"79","title":"Master of Theology","type":"Degree"},
    {"id":"80","title":"Nuclear Engineer","type":"Degree"},
    {"id":"81","title":"Doctor of Optometry","type":"Degree"},
    {"id":"82","title":"Doctor of Pharmacy","type":"Degree"},
    {"id":"83","title":"Bachelor of Philosophy","type":"Degree"},
    {"id":"84","title":"Doctor of Philosophy","type":"Degree"},
    {"id":"85","title":"BSc (Bachelor of Science)","type":"Degree"},
    {"id":"86","title":"Doctor of Science","type":"Degree"},
    {"id":"87","title":"Doctor of Juridical Science or Doctor of the Science of Law","type":"Degree"},
    {"id":"88","title":"Doctor of Social Science","type":"Degree"},
    {"id":"89","title":"Bachelor of Theology","type":"Degree"},
    {"id":"90","title":"Doctor of Theology","type":"Degree"},
    {"id":"91","title":"Master of Theology","type":"Degree"},
    {"id":"92","title":"Computer Science","type":"Matriculation"},
    {"id":"93","title":"Pre-Engineering","type":"Intermediate"},
    {"id":"97","title":"General","type":"Matriculation"},
    {"id":"101","title":"Science","type":"Matriculation"},
    {"id":"105","title":"Pre-Medical","type":"Intermediate"},
    {"id":"106","title":"Bachelor of Commerce","type":"Degree"},
    {"id":"114","title":"Commerce","type":"Intermediate"},
    {"id":"115","title":"Basics of Computer and Internet","type":"Certificate"},
    {"id":"117","title":"House Keeping","type":"Certificate"},
    {"id":"118","title":"Hotel Management and Theoretical Course","type":"Certificate"},
    {"id":"119","title":"Diploma in Commerce","type":"Diploma"},
    {"id":"120","title":"BCom (Hons)","type":"Degree"},
    {"id":"121","title":"Quality Assurance and Managment","type":"Certificate"},
    {"id":"122","title":"Diploma of Associate Engineer","type":"Diploma"},
    {"id":"123","title":"Achitectural Conservation Course","type":"Certificate"},
    {"id":"125","title":"Masters in Economics","type":"Degree"},
    {"id":"132","title":"Training Workshop","type":"Certificate"},
    {"id":"138","title":"Basic Computers","type":"Diploma"},
    {"id":"141","title":"MCom (Master of Commerce)","type":"Degree"},
    {"id":"144","title":"Professional I","type":"Degree"},
    {"id":"147","title":"Lauguage Course","type":"Certificate"},
    {"id":"151","title":"Visiting Teacher Programm","type":"Certificate"},
    {"id":"154","title":" Elementary Hotel Management","type":"Diploma"},
    {"id":"155","title":"Practical Accounting","type":"Certificate"},
    {"id":"159","title":"Computer Hardware and Networking","type":"Diploma"},
    {"id":"160","title":"Vocational Training in Sewing, Cutting, Embroidery, Machine Knitting","type":"Certificate"},
    {"id":"161","title":"Bachelor of Arts (Hons)","type":"Degree"},
    {"id":"162","title":"Business Administration","type":"Diploma"},
    {"id":"164","title":"Basic Computers","type":"Certificate"},
    {"id":"169","title":"Computer Advance Course","type":"Certificate"},
    {"id":"170","title":"MS Office","type":"Certificate"},
    {"id":"172","title":"Construction Management","type":"Diploma"},
    {"id":"173","title":"Civil Technology","type":"Diploma"},
    {"id":"177","title":"Humanities","type":"Intermediate"},
    {"id":"179","title":"BCom (Bachelor of Commerce)","type":"Degree"},
    {"id":"181","title":"BE (Bachelor of Engineering)","type":"Degree"},
    {"id":"184","title":"BTech(Bachelor of Technology)","type":"Degree"},
    {"id":"185","title":"Auto CAD &3D","type":"Certificate"},
    {"id":"186","title":"Project Management","type":"Certificate"},
    {"id":"187","title":"Secretariat Procedures and Practice","type":"Certificate"},
    {"id":"189","title":"Training ","type":"Certificate"},
    {"id":"195","title":"Water & Sanitation Course","type":"Certificate"},
    {"id":"196","title":"Staff Development","type":"Certificate"},
    {"id":"197","title":"Pre Service Training","type":"Certificate"},
    {"id":"201","title":"Clinical Lab Tecnology","type":"Diploma"},
    {"id":"203","title":"Social Development","type":"Certificate"},
    {"id":"204","title":"Management Skills","type":"Certificate"},
    {"id":"205","title":"Disaster Assesment Training","type":"Certificate"},
    {"id":"206","title":"Communication And Analytical Skill","type":"Certificate"},
    {"id":"207","title":"Local Manufacture:Potential","type":"Short Course"},
    {"id":"208","title":"Environmental Impact Assessment","type":"Certificate"},
    {"id":"209","title":"Developing a Social Marketing Campaign","type":"Certificate"},
    {"id":"210","title":"Environmental Checklist and Guidelines","type":"Certificate"},
    {"id":"211","title":"Revit Architecture","type":"Certificate"},
    {"id":"212","title":"N\/A","type":"Intermediate"},
    {"id":"214","title":"N\/A","type":"Primary"},
    {"id":"221","title":"Associate F. Accountants","type":"Certificate"},
    {"id":"222","title":"Accounts","type":"Certificate"},
    {"id":"226","title":"Post Graduate","type":"Diploma"},
    {"id":"227","title":"MTM","type":"Diploma"},
    {"id":"228","title":"Diploma in Logistics and Supply Chain Management","type":"Diploma"},
    {"id":"229","title":"Humanities","type":"Matriculation"},
    {"id":"230","title":"MIDWIFERY","type":"Diploma"},
    {"id":"232","title":"Bachelor of Environmental Sciences","type":"Degree"},
    {"id":"234","title":"M.D.S.","type":"Degree"},
    {"id":"238","title":"BTech (Bachelor of Technology.Hons)","type":"Degree"},
    {"id":"239","title":"AutoCad","type":"Diploma"},
    {"id":"240","title":"Workshop","type":"Certificate"},
    {"id":"241","title":"Epanet Program","type":"Short Course"},
    {"id":"242","title":"International Rural Development Planning","type":"Diploma"},
    {"id":"249","title":"Sesmic Analysis And Design","type":"Certificate"},
    {"id":"253","title":"Commerce","type":"Certificate"},
    {"id":"254","title":"Finance & Accountancy","type":"Diploma"},
    {"id":"256","title":"I.C.M.A.-F1","type":"Diploma"},
    {"id":"261","title":"Communication skills and report writing","type":"Certificate"},
    {"id":"262","title":"Civil Drafting","type":"Certificate"},
    {"id":"263","title":"Qualified Competative exam","type":"Diploma"},
    {"id":"264","title":"Architecture Technology","type":"Diploma"},
    {"id":"266","title":"PGD","type":"Diploma"},
    {"id":"268","title":"Problem solving and Decision Making","type":"Degree"},
    {"id":"269","title":"Problem solving and Decision Making","type":"Certificate"},
    {"id":"270","title":"Social Organizer.","type":"Short Course"},
    {"id":"271","title":"Community Mobilzation","type":"Short Course"},
    {"id":"272","title":"Diploma In Education","type":"Diploma"},
    {"id":"273","title":"BBA Hons","type":"Degree"},
    {"id":"277","title":"ICMA PGD1","type":"Diploma"},
    {"id":"279","title":"N\/A","type":"Matriculation"},
    {"id":"285","title":"Information & Communication Technology","type":"Short Course"},
    {"id":"287","title":"Microsoft Unlimited Potential Course","type":"Short Course"},
    {"id":"288","title":"CT","type":"Certificate"},
    {"id":"289","title":"Draftsman Civil,Auto cad","type":"Short Course"},
    {"id":"290","title":"Field Based Training course","type":"Short Course"},
    {"id":"301","title":"Primary Teaching.","type":"Diploma"},
    {"id":"302","title":"Computers, English","type":"Short Course"},
    {"id":"303","title":"Youth Development","type":"Short Course"},
    {"id":"304","title":"AutoCad","type":"Short Course"},
    {"id":"305","title":"Skill Development","type":"Short Course"},
    {"id":"306","title":"Computer Science","type":"Intermediate"},
    {"id":"315","title":"M.I.R.","type":"Degree"},
    {"id":"316","title":"Information Technology","type":"Diploma"},
    {"id":"317","title":"Middle","type":"Primary"},
    {"id":"318","title":"In-House Training","type":"Short Course"},
    {"id":"319","title":"OICD Agricultural Communication","type":"Short Course"},
    {"id":"320","title":"Management Staff","type":"Short Course"},
    {"id":"322","title":"Techniques Course","type":"Short Course"},
    {"id":"323","title":"Certified Trainings","type":"Short Course"},
    {"id":"324","title":"Certified Workshop","type":"Short Course"},
    {"id":"327","title":"Masters of Development Studies","type":"Degree"},
    {"id":"329","title":"Certified Program","type":"Short Course"},
    {"id":"332","title":"Computer Application","type":"Certificate"},
    {"id":"333","title":"Honorary Manpower Development Program","type":"Certificate"},
    {"id":"335","title":"Science","type":"A-Level"},
    {"id":"336","title":"Science","type":"O-Level"},
    {"id":"338","title":"Post Graduate Diploma In Economics & Finance","type":"Diploma"},
    {"id":"341","title":"Surveyor TRADE","type":"Short Course"},
    {"id":"344","title":"PTC","type":"Certificate"},
    {"id":"347","title":"HOAP Hotel Management Training Programme","type":"Short Course"},
    {"id":"356","title":"Human Resource Development","type":"Certificate"},
    {"id":"357","title":"Finance Training","type":"Certificate"},
    {"id":"360","title":"New Trends Hyderabad","type":"Diploma"},
    {"id":"361","title":"Computer Science","type":"Diploma"},
    {"id":"364","title":"Civil Supervisor","type":"Short Course"},
    {"id":"365","title":"PPRA rules","type":"Short Course"},
    {"id":"366","title":"Post Graduate","type":"Certificate"},
    {"id":"373","title":"Certificate Of Teaching (CT)","type":"Diploma"},
    {"id":"374","title":"Continuing Education","type":"Short Course"},
    {"id":"377","title":"IT Support","type":"Diploma"},
    {"id":"378","title":"Multimedia","type":"Short Course"},
    {"id":"379","title":"ACCA","type":"Certificate"},
    {"id":"385","title":"Bachelor of Computer Science","type":"Degree"},
    {"id":"389","title":"M.Phil","type":"Degree"},
    {"id":"390","title":"Trade Technology","type":"Certificate"},
    {"id":"392","title":"Industrail Electronics","type":"Certificate"},
    {"id":"398","title":"Advance Diploma","type":"Diploma"},
    {"id":"400","title":"Microsoft Certified Professional","type":"Certificate"},
    {"id":"406","title":"ACA (Associate Chartered Accountant)","type":"Certificate"},
    {"id":"407","title":"CISA (Certified Information System Auditor)","type":"Certificate"},
    {"id":"411","title":"Economics","type":"O-Level"},
    {"id":"412","title":"Economics","type":"A-Level"},
    {"id":"414","title":"Project Management","type":"Diploma"},
    {"id":"415","title":"Masters in International Humanitarian Assistance","type":"Degree"},
    {"id":"418","title":"Certified Chartered Accountant","type":"Certificate"},
    {"id":"419","title":"Cisco Certified Academy Instructor","type":"Certificate"},
    {"id":"420","title":"Certified Wireles Network Associate","type":"Certificate"},
    {"id":"421","title":"Linux System Administrator (SA1)","type":"Certificate"},
    {"id":"422","title":"Configuring and Administring Microsoft Exchange Server 2003","type":"Certificate"},
    {"id":"423","title":"Cisco Certified Network Associate Security","type":"Certificate"},
    {"id":"424","title":"Windows Server 2008 Active Directory, Configuring ","type":"Certificate"},
    {"id":"425","title":"Windows Server 2008 Network Infrastructure, Configuring","type":"Certificate"},
    {"id":"426","title":"Implementing Cisco IOS Network Security","type":"Certificate"},
    {"id":"427","title":"Building Converged Cisco Multilayer Switched Networks","type":"Certificate"},
    {"id":"428","title":"Building Converged Cisco Multilayer Switched Networks","type":"Certificate"},
    {"id":"429","title":"Building Scalable Cisco Internetworks","type":"Certificate"},
    {"id":"430","title":"Cisco Certified Network Associate","type":"Certificate"},
    {"id":"431","title":"CCNA Exploration & LAN Switching and Wireless","type":"Certificate"},
    {"id":"436","title":"AutoCAD","type":"Certificate"},
    {"id":"438","title":"BSc Hons (Bachelor of Science)","type":"Degree"},
    {"id":"447","title":"BSc Hons (Bachelor of Science)","type":"Degree"},
    {"id":"448","title":"Quantity Surveying \"Measurement of Building Works\"","type":"Certificate"},
    {"id":"449","title":"General Construction Course","type":"Certificate"},
    {"id":"450","title":"CIA (Certified Internal Auditor)","type":"Certificate"},
    {"id":"451","title":"APA (Assosciate Public Accountant)","type":"Certificate"}
    ],
    specialization: [
        'IT',
        'Software Enginering',
        'Economics',
        'Pak Study',
        'BBA',
    ],
    };
      
export default education
    
    